id: 131f13ebd19f466882f1891cf7b2229f
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_679-Dharan%C4%AB_Praising_the_Qualities_of_the_Immeasurable_One-v2
  language: en
  author: ''
  volume: {}
